import { useNavigate } from 'react-router-dom'
import { Check, Download, FileText, MapPinned, RefreshCcw, Save, Search, Send, Settings2 } from 'lucide-react'
import { useState } from 'react'
import { alerts, areas, incidents, hotspots } from '../data/mockData'
import type { Hotspot, Incident } from '../types'
import { AIIntelligence } from '../components/AIIntelligence'
import { DistributionChart, TrendChart } from '../components/Charts'
import { CrimeMap } from '../components/CrimeMap'
import { HotspotPanel } from '../components/HotspotPanel'
import { IncidentDrawer } from '../components/IncidentDrawer'
import { IncidentTable } from '../components/IncidentTable'
import { PatrolPlanner } from '../components/PatrolPlanner'
import { PredictionForm } from '../components/PredictionForm'
import { RiskList } from '../components/RiskList'
import { LiveMapInsights } from '../components/LiveMapInsights'
import { Badge, Button, Eyebrow, LinkAction, SectionHeading, Surface } from '../components/ui'

export function CrimeMapPage() {
  const navigate = useNavigate(); const [selected, setSelected] = useState<Hotspot | null>(hotspots[0]); const [focus, setFocus] = useState<Hotspot | null>(hotspots[0]); const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null)
  return <><div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><Eyebrow className="mb-2">Geospatial intelligence Ã‚Â· live</Eyebrow><h2 className="text-[28px] font-semibold tracking-[-.055em] text-warm">Crime map <span className="text-softred">/ signal field</span></h2><p className="mt-2 text-xs text-muted">A synthetic risk surface for PuducherryÃ¢â‚¬â„¢s current operating picture.</p></div><Button onClick={() => navigate('/patrol-planning')} variant="primary"><MapPinned size={14} /> Generate patrol plan</Button></div><div className="grid gap-5 2xl:grid-cols-[minmax(0,1.45fr)_380px]"><CrimeMap className="min-h-[660px]" onHotspotSelect={(spot) => { setSelected(spot); setFocus(spot) }} onIncidentSelect={setSelectedIncident} focusArea={focus} /><div className="space-y-5"><HotspotPanel hotspot={selected} onViewMap={() => setFocus(selected)} onPatrol={() => navigate('/patrol-planning')} /><Surface className="p-5"><Eyebrow className="mb-3">Map filters</Eyebrow><div className="space-y-3"><label className="flex items-center justify-between text-xs text-muted"><span>Crime categories</span><select className="rounded border border-border bg-surface px-2 py-1.5 text-[10px] text-warm"><option>All categories</option><option>Theft</option><option>Vehicle Theft</option><option>Burglary</option></select></label><label className="flex items-center justify-between text-xs text-muted"><span>Risk levels</span><select className="rounded border border-border bg-surface px-2 py-1.5 text-[10px] text-warm"><option>All levels</option><option>High</option><option>Medium</option><option>Low</option></select></label><label className="flex items-center justify-between text-xs text-muted"><span>Heatmap intensity</span><input type="range" defaultValue="82" className="accent-signal" /></label></div></Surface><LiveMapInsights /></div></div></div><IncidentDrawer incident={selectedIncident} onClose={() => setSelectedIncident(null)} onShowMap={() => setSelectedIncident(null)} /></>
}

export function AIAssistantPage() { const navigate = useNavigate(); return <div className="mx-auto max-w-[1120px] space-y-7"><div><Eyebrow className="mb-2">Decision support Ã‚Â· AI console</Eyebrow><h2 className="text-[30px] font-semibold tracking-[-.055em] text-warm">Ask the signal. <span className="text-softred">Move with context.</span></h2><p className="mt-2 max-w-[600px] text-xs leading-5 text-muted">A focused intelligence interface for synthetic pattern detection, risk ranking, and field recommendations.</p></div><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><AIIntelligence onViewMap={() => navigate('/crime-map')} /><Surface className="grid min-h-[500px] place-items-center p-8 text-center"><div><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl border border-crimson/50 bg-burgundy text-signal"><Search size={22} /></div><Eyebrow>Query examples</Eyebrow><div className="mt-3 space-y-2 text-left">{['Show vehicle theft hotspots after 8 PM', 'Compare crime rates with last week', 'Find unusual patterns near Beach Road', 'Suggest patrol areas for the next shift'].map((text) => <div key={text} className="rounded-lg border border-border bg-surface px-3 py-2.5 text-[11px] text-warm">{text}</div>)}</div></div></Surface></div></div> }

export function AnalyticsPage() { const [selected, setSelected] = useState<Incident | null>(null); return <div className="space-y-7"><div><Eyebrow className="mb-2">Intelligence / trends and patterns</Eyebrow><h2 className="text-[28px] font-semibold tracking-[-.055em] text-warm">The city leaves a <span className="text-softred">pattern.</span></h2><p className="mt-2 text-xs text-muted">Thirty-day signal movement across synthetic incident records.</p></div><div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><TrendChart /><DistributionChart /></div><div className="grid gap-5 xl:grid-cols-[.7fr_1.3fr]"><RiskList /><div><SectionHeading eyebrow="Incident register" title="Recent incidents" detail="Severity and status across the current intelligence window" /><IncidentTable data={incidents} onSelect={setSelected} /></div></div><IncidentDrawer incident={selected} onClose={() => setSelected(null)} onShowMap={() => setSelected(null)} /></div> }

export function PredictionPage() { const navigate = useNavigate(); return <div className="space-y-7"><div><Eyebrow className="mb-2">Intelligence / risk forecast</Eyebrow><h2 className="text-[28px] font-semibold tracking-[-.055em] text-warm">Predict the next <span className="text-softred">high-risk area.</span></h2><p className="mt-2 text-xs text-muted">A transparent mock forecast that exposes the signal behind the score.</p></div><PredictionForm onViewMap={() => navigate('/crime-map')} /></div> }

export function PatrolPlanningPage() { return <div className="space-y-7"><div><Eyebrow className="mb-2">Field operations / optimization</Eyebrow><h2 className="text-[28px] font-semibold tracking-[-.055em] text-warm">Move the right unit <span className="text-softred">before the peak.</span></h2><p className="mt-2 text-xs text-muted">Simulate coverage decisions against the live synthetic risk layer.</p></div><PatrolPlanner /></div> }

export function IncidentsPage() { const [selected, setSelected] = useState<Incident | null>(null); const navigate = useNavigate(); return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><Eyebrow className="mb-2">Records / live incidents</Eyebrow><h2 className="text-[28px] font-semibold tracking-[-.055em] text-warm">Incident <span className="text-softred">register.</span></h2><p className="mt-2 text-xs text-muted">Synthetic field records synced to the current operational picture.</p></div><Button onClick={() => navigate('/reports')} variant="secondary"><FileText size={14} /> Daily report</Button></div><IncidentTable data={incidents} onSelect={setSelected} /><IncidentDrawer incident={selected} onClose={() => setSelected(null)} onShowMap={() => navigate('/crime-map')} /></div> }

export function ReportsPage() { const [generated, setGenerated] = useState(false); const [exported, setExported] = useState(false); return <div className="mx-auto max-w-[1120px] space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><Eyebrow className="mb-2">Briefing / intelligence report</Eyebrow><h2 className="text-[28px] font-semibold tracking-[-.055em] text-warm">Daily intelligence <span className="text-softred">report.</span></h2><p className="mt-2 text-xs text-muted">A concise field brief assembled from the current synthetic signal set.</p></div><div className="flex gap-2"><Button onClick={() => setGenerated(true)} variant="primary"><RefreshCcw size={14} /> Generate report</Button><Button onClick={() => setExported(true)} variant="secondary"><Download size={14} /> Export PDF</Button></div></div><Surface className="overflow-hidden"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-border bg-gradient-to-r from-[#e8f0eb] to-card p-6"><div><Eyebrow className="mb-2">PUDUCHERRY POLICE Ã‚Â· CRIMEMAP AI</Eyebrow><h3 className="text-[22px] font-semibold tracking-[-.04em] text-warm">DAILY INTELLIGENCE REPORT</h3><div className="mono mt-2 text-[10px] text-muted">13 OCT 2026 Ã‚Â· 19:42 IST Ã‚Â· INTERNAL PROTOTYPE</div></div><div className="text-right"><div className="eyebrow">Report status</div><div className={`mt-2 mono text-[11px] ${generated ? 'text-[#9ee0bc]' : 'text-muted'}`}>{generated ? 'GENERATED / READY' : 'DRAFT / NOT GENERATED'}</div></div></div><div className="grid gap-px bg-border sm:grid-cols-2">{[['Crime summary', '27 incidents logged today. Vehicle theft leads the active risk picture.'], ['Hotspot analysis', 'White Town remains the primary risk zone at 92 / 100 with a 19:00Ã¢â‚¬â€œ23:00 peak.'], ['Emerging patterns', 'Three high-risk areas share an evening access-corridor signature.'], ['Patrol recommendation', 'Maintain 92% planned coverage and prioritize White Town / M.G. Road.'], ['Active alerts', '03 open alerts: vehicle theft cluster, coverage gap, and Beach Road uplift.'], ['Analyst note', generated ? 'Report generated from the 13 OCT 2026 synthetic intelligence snapshot.' : 'Generate the report to lock the current intelligence snapshot.']].map(([title, body]) => <div key={title} className="bg-card p-5"><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-signal" /><div className="text-xs font-semibold text-warm">{title}</div></div><p className="mt-3 text-xs leading-5 text-muted">{body}</p></div>)}</div><div className="flex items-center justify-between border-t border-border p-5 text-[10px] text-muted"><span>Frontend-only prototype Ã‚Â· all records synthetic</span>{exported && <span className="flex items-center gap-1 text-[#9ee0bc]"><Check size={12} /> Export queued</span>}</div></Surface></div> }

export function SettingsPage() { const [saved, setSaved] = useState(false); return <div className="mx-auto max-w-[960px] space-y-7"><div><Eyebrow className="mb-2">System / preferences</Eyebrow><h2 className="text-[28px] font-semibold tracking-[-.055em] text-warm">System settings.</h2><p className="mt-2 text-xs text-muted">Keep the command center aligned to the stationÃ¢â‚¬â„¢s operating rhythm.</p></div><div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Surface className="p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full border border-crimson/50 bg-burgundy text-softred"><Settings2 size={17} /></div><div><div className="text-sm font-semibold text-warm">Inspector profile</div><div className="mt-1 text-[10px] text-muted">Active command identity</div></div></div><div className="mt-6 space-y-4 text-xs"><div><div className="eyebrow">Name</div><div className="mt-2 rounded-lg border border-border bg-surface px-3 py-2.5 text-warm">Inspector</div></div><div><div className="eyebrow">Station</div><div className="mt-2 rounded-lg border border-border bg-surface px-3 py-2.5 text-warm">White Town Police Station</div></div><div><div className="eyebrow">System status</div><div className="mt-2 flex items-center gap-2 rounded-lg border border-[#376653]/60 bg-[#376653]/10 px-3 py-2.5 text-[#9ee0bc]"><span className="h-1.5 w-1.5 rounded-full bg-[#6aa883]" />System operational</div></div></div></Surface><Surface className="p-5"><div className="flex items-center justify-between border-b border-border pb-4"><div><div className="text-sm font-semibold text-warm">Preferences</div><div className="mt-1 text-xs text-muted">Prototype controls for map and notifications</div></div><Button onClick={() => setSaved(true)} variant={saved ? 'secondary' : 'primary'} size="sm">{saved ? <Check size={13} /> : <Save size={13} />}{saved ? 'Saved' : 'Save changes'}</Button></div><div className="mt-5 space-y-5">{[['Notification preferences', 'Alert me when high-risk zones change', true], ['Map preferences', 'Show hotspot labels by default', true], ['Theme', 'White / blue operations mode', false]].map(([title, detail, checked]) => <div key={String(title)} className="flex items-center justify-between gap-4"><div><div className="text-xs font-medium text-warm">{title}</div><div className="mt-1 text-[10px] text-muted">{detail}</div></div><div className={`flex h-6 w-11 items-center rounded-full border p-0.5 ${checked ? 'justify-end border-crimson bg-crimson/30' : 'justify-start border-border bg-surface'}`}><span className={`h-4 w-4 rounded-full ${checked ? 'bg-softred' : 'bg-muted'}`} /></div></div>)}</div></Surface></div></div> }
