import { useState } from 'react'
import { ArrowUpRight, AudioLines, Bot, CornerDownLeft, Sparkles } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { aiInsight } from '../data/mockData'
import { api } from '../lib/api'
import { Button, Eyebrow, Surface } from './ui'

const prompts = ['Show theft hotspots after 8 PM', 'Compare crime rates', 'Find unusual patterns', 'Suggest patrol areas']

export function AIIntelligence({ onViewMap }: { onViewMap?: () => void }) {
  const [response, setResponse] = useState(aiInsight); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(false)
  const runPrompt = async (prompt: string) => { setQuery(''); setLoading(true); try { setResponse(await api.aiQuery(prompt)) } catch { setResponse({ ...aiInsight, body: 'Backend unavailable. Showing the last synthetic briefing snapshot.' }) } finally { setLoading(false) } }
  return <Surface className="flex h-full min-h-[500px] flex-col overflow-hidden">
    <div className="flex items-start justify-between border-b border-border px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center border border-border bg-panel text-signal"><Bot size={15} /></div><div><div className="mono text-[11px] font-medium tracking-[.04em] text-warm">CRIMEMAP INTELLIGENCE</div><div className="mono mt-1 text-[8px] uppercase tracking-[.12em] text-muted">AI decision support / console 03</div></div></div><span className="mono border border-[#5d7564] bg-[#28332c] px-1.5 py-1 text-[8px] uppercase tracking-[.1em] text-[#b6d6bd]">{loading ? 'Querying' : 'Live data'}</span></div>
    <div className="flex-1 space-y-5 p-5"><div><Eyebrow className="mb-2">Briefing assistant · 19:42</Eyebrow><h3 className="text-[21px] font-semibold tracking-[-.04em] text-warm">Good evening, Inspector.</h3><p className="mt-2 max-w-[330px] text-xs leading-5 text-muted">Query a pattern, hotspot, or field recommendation. The console returns database-backed operational context.</p></div>
      <div><div className="mb-2 flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.13em] text-muted"><Sparkles size={11} className="text-signal" />Quick actions</div><div className="grid grid-cols-1 gap-1.5">{prompts.map((prompt) => <button key={prompt} onClick={() => runPrompt(prompt)} className="flex items-center justify-between border border-border bg-panel px-3 py-2.5 text-left text-[10px] text-warm transition-colors hover:border-[#62696d] hover:bg-surface"><span>{prompt}</span><ArrowUpRight size={12} className="text-muted" /></button>)}</div></div>
      <AnimatePresence mode="wait"><motion.div key={response.body} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -4 }} className="border border-border bg-panel p-4"><div className="mono text-[8px] uppercase tracking-[.15em] text-softred">{response.title}</div><p className="mt-2 text-[11px] leading-5 text-warm/80">{response.body}</p><div className="mt-4 space-y-2">{response.areas.map((area, index) => <div key={area.name} className="flex items-center justify-between border-b border-border/70 pb-2 last:border-0 last:pb-0"><div className="flex items-center gap-2"><span className="mono text-[9px] text-muted">0{index + 1}</span><span className="text-[11px] font-medium text-warm">{area.name}</span></div><span className="mono text-[11px] font-medium text-softred">{area.score}</span></div>)}</div><div className="mt-4 border-t border-border/70 pt-3"><div className="mono text-[8px] uppercase tracking-[.12em] text-muted">Peak activity <span className="ml-2 text-warm">{response.peakTime}</span></div><p className="mt-2 text-[11px] leading-5 text-warm/75"><span className="text-muted">Recommendation: </span>{response.recommendation}</p></div><Button onClick={onViewMap} variant="ghost" size="sm" className="mt-3 h-7 px-0 text-[9px]">View on map <CornerDownLeft size={12} /></Button></motion.div></AnimatePresence>
    </div><div className="border-t border-border p-4"><div className="flex items-center gap-2 border border-border bg-panel px-3"><AudioLines size={13} className="text-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && query.trim()) runPrompt(query) }} placeholder="Ask about crime intelligence..." className="min-w-0 flex-1 bg-transparent py-3 text-[10px] text-warm outline-none placeholder:text-muted" /><button onClick={() => query.trim() && runPrompt(query)} className="text-muted transition-colors hover:text-signal"><CornerDownLeft size={13} /></button></div></div>
  </Surface>
}
