import { ArrowUpRight, Clock3, MapPin, TrendingUp } from 'lucide-react'
import type { Hotspot } from '../types'
import { Button, Eyebrow, Surface } from './ui'
import { riskTone } from '../lib/utils'

export function HotspotPanel({ hotspot, onViewMap, onPatrol }: { hotspot: Hotspot | null; onViewMap?: () => void; onPatrol?: () => void }) {
  if (!hotspot) return <Surface className="flex min-h-[230px] items-center justify-center p-5 text-center"><div><div className="mx-auto mb-3 flex h-9 w-9 items-center justify-center border border-border bg-panel text-muted"><MapPin size={16} /></div><div className="text-sm font-semibold text-warm">Select a hotspot</div><p className="mt-1 max-w-[210px] text-xs leading-5 text-muted">Click a signal on the map to inspect its risk profile and recommended response.</p></div></Surface>
  return <Surface className="overflow-hidden"><div className="border-b border-border bg-card p-5"><div className="flex items-start justify-between"><div><Eyebrow className="mb-2">Selected hotspot · live</Eyebrow><h3 className="text-[19px] font-semibold tracking-[-.035em] text-warm">{hotspot.name}</h3><div className="mono mt-1 text-[9px] text-muted">{hotspot.coordinates[1].toFixed(4)}° N · {hotspot.coordinates[0].toFixed(4)}° E</div></div><div className={`flex h-11 w-11 flex-col items-center justify-center border ${riskTone(hotspot.riskScore) === 'high' ? 'border-signal/70 bg-signal/10' : 'border-border bg-panel'}`}><div className="mono text-[17px] font-medium text-warm">{hotspot.riskScore}</div><div className="mono text-[8px] uppercase tracking-[.1em] text-softred">risk</div></div></div></div><div className="grid grid-cols-2 gap-px bg-border"><div className="bg-card p-4"><div className="eyebrow">Incidents</div><div className="mt-2 text-[20px] font-semibold text-warm">{hotspot.incidentCount}</div></div><div className="bg-card p-4"><div className="eyebrow">Change</div><div className="mt-2 flex items-center gap-1 text-[20px] font-semibold text-softred"><TrendingUp size={15} />{hotspot.trend}%</div></div><div className="bg-card p-4"><div className="eyebrow">Peak window</div><div className="mt-2 flex items-center gap-1 text-xs font-medium text-warm"><Clock3 size={13} className="text-muted" />{hotspot.peakTime}</div></div><div className="bg-card p-4"><div className="eyebrow">Primary crime</div><div className="mt-2 text-xs font-medium text-warm">{hotspot.primaryPattern}</div></div></div><div className="flex gap-2 border-t border-border p-4"><Button onClick={onViewMap} variant="secondary" size="sm" className="flex-1">View analysis <ArrowUpRight size={13} /></Button><Button onClick={onPatrol} variant="primary" size="sm" className="flex-1">Plan patrol <ArrowUpRight size={13} /></Button></div></Surface>
}
