import { ArrowDownUp, Filter, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { Incident } from '../types'
import { Badge, Button, Surface } from './ui'
import { riskTone } from '../lib/utils'

export function IncidentTable({ data, onSelect, compact = false }: { data: Incident[]; onSelect: (incident: Incident) => void; compact?: boolean }) {
  const [query, setQuery] = useState('')
  const [severity, setSeverity] = useState('ALL')
  const [sortDesc, setSortDesc] = useState(true)
  const filtered = useMemo(() => data.filter((item) => { const haystack = `${item.id} ${item.crime} ${item.location}`.toLowerCase(); return haystack.includes(query.toLowerCase()) && (severity === 'ALL' || item.severity === severity) }).sort((a, b) => sortDesc ? b.id.localeCompare(a.id) : a.id.localeCompare(b.id)), [data, query, severity, sortDesc])
  return <Surface className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div className="flex items-center gap-2"><div className="flex h-9 w-[220px] items-center gap-2 rounded-lg border border-border bg-surface px-3"><Search size={13} className="text-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search incidents…" className="min-w-0 flex-1 bg-transparent text-[11px] text-warm outline-none placeholder:text-muted" /></div><select value={severity} onChange={(event) => setSeverity(event.target.value)} className="h-9 rounded-lg border border-border bg-surface px-2 text-[10px] text-muted outline-none"><option value="ALL">All severity</option><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option></select></div><div className="flex items-center gap-2"><Button variant="ghost" size="sm" className="h-8" onClick={() => setSeverity('ALL')}><Filter size={12} />Filters</Button><Button variant="ghost" size="sm" className="h-8" onClick={() => setSortDesc((value) => !value)}><ArrowDownUp size={12} />Sort</Button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-border bg-surface/70">{['ID', 'Crime', 'Location', 'Date / time', 'Severity', 'Status'].map((heading) => <th key={heading} className="px-4 py-3 font-mono text-[9px] font-medium uppercase tracking-[.14em] text-muted">{heading}</th>)}</tr></thead><tbody>{filtered.slice(0, compact ? 5 : filtered.length).map((item) => <tr key={item.id} onClick={() => onSelect(item)} className="group cursor-pointer border-b border-border/70 transition-colors hover:bg-burgundy/40"><td className="px-4 py-3 mono text-[10px] text-softred">{item.id}</td><td className="px-4 py-3 text-xs font-medium text-warm">{item.crime}</td><td className="px-4 py-3 text-xs text-muted">{item.location}</td><td className="px-4 py-3"><div className="text-[11px] text-warm/80">{item.date}</div><div className="mono mt-1 text-[9px] text-muted">{item.time}</div></td><td className="px-4 py-3"><Badge tone={riskTone(item.severity === 'HIGH' ? 90 : item.severity === 'MEDIUM' ? 70 : 40)}>{item.severity}</Badge></td><td className="px-4 py-3"><span className="text-[10px] uppercase tracking-[.08em] text-muted">{item.status}</span></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-8 text-center text-xs text-muted">No incidents match the current query.</div>}</div></Surface>
}
