import { ArrowUpRight, Copy, MapPin, ShieldAlert, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import type { Incident } from '../types'
import { Badge, Button, Eyebrow } from './ui'
import { riskTone } from '../lib/utils'

export function IncidentDrawer({ incident, onClose, onShowMap }: { incident: Incident | null; onClose: () => void; onShowMap?: () => void }) {
  return <AnimatePresence>{incident && <><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose} className="fixed inset-0 z-40 bg-slate-900/20 backdrop-blur-sm" /><motion.aside initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', damping: 28, stiffness: 260 }} className="fixed inset-y-0 right-0 z-50 flex w-full max-w-[420px] flex-col border-l border-border bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-border p-5"><div><Eyebrow className="mb-2">Incident detail Â· live record</Eyebrow><div className="flex items-center gap-2"><h2 className="text-[20px] font-semibold text-warm">INCIDENT {incident.id}</h2><Badge tone={riskTone(incident.severity === 'HIGH' ? 90 : incident.severity === 'MEDIUM' ? 70 : 40)}>{incident.severity}</Badge></div></div><button onClick={onClose} className="text-muted hover:text-warm"><X size={18} /></button></div><div className="flex-1 overflow-y-auto p-5"><div className="rounded-xl border border-[#bdd3c7] bg-[#e8f0eb] p-4"><div className="flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg border border-blue-200 bg-white text-signal"><ShieldAlert size={17} /></div><div><div className="text-sm font-semibold text-warm">{incident.crime}</div><div className="mt-1 flex items-center gap-1 text-xs text-muted"><MapPin size={12} className="text-signal" />{incident.location}</div></div></div><p className="mt-4 text-xs leading-5 text-[#5f6c65]">{incident.summary}</p></div><div className="mt-5 grid grid-cols-2 gap-3">{[['Date', incident.date], ['Time', incident.time], ['Status', incident.status], ['Coordinates', `${incident.coordinates[1].toFixed(4)} N`], ['Nearby incidents', incident.nearbyIncidents], ['Similar cases', incident.similarCases]].map(([label, value]) => <div key={String(label)} className="rounded-lg border border-border bg-panel p-3"><div className="eyebrow">{label}</div><div className="mono mt-2 text-[11px] text-warm">{value}</div></div>)}</div><div className="mt-5"><Eyebrow className="mb-3">Signal notes</Eyebrow><div className="space-y-2 text-xs text-muted"><div className="flex gap-2"><span className="mt-1 h-1.5 w-1.5 rounded-full bg-signal" />Matched against {incident.similarCases} prior synthetic records.</div><div className="flex gap-2"><span className="mt-1 h-1.5 w-1.5 rounded-full bg-signal" />Activity is within the current high-attention window.</div><div className="flex gap-2"><span className="mt-1 h-1.5 w-1.5 rounded-full bg-signal" />Coordinate packet is ready for map overlay.</div></div></div></div><div className="flex gap-2 border-t border-border p-5"><Button onClick={onShowMap} variant="primary" className="flex-1">Show on map <ArrowUpRight size={13} /></Button><Button variant="secondary" className="flex-1"><Copy size={13} />Similar cases</Button></div></motion.aside></>}
  </AnimatePresence>
}
