import { Bell, Menu, Search, ShieldCheck } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useMemo, useState } from 'react'
import { Button } from './ui'

const meta: Record<string, { title: string; crumb: string }> = {
  '/dashboard': { title: 'Command overview', crumb: '01 / command' }, '/crime-map': { title: 'Crime map', crumb: '02 / geospatial intelligence' }, '/ai-assistant': { title: 'AI assistant', crumb: '03 / decision support' }, '/analytics': { title: 'Analytics', crumb: '04 / trends and patterns' }, '/prediction': { title: 'Prediction', crumb: '05 / risk forecast' }, '/patrol-planning': { title: 'Patrol planning', crumb: '06 / field operations' }, '/incidents': { title: 'Incident register', crumb: '07 / live records' }, '/reports': { title: 'Daily report', crumb: '08 / briefing' }, '/settings': { title: 'Settings', crumb: '09 / system' },
}

export function Topbar({ onMenu }: { onMenu: () => void }) {
  const location = useLocation(); const navigate = useNavigate(); const [query, setQuery] = useState(''); const current = meta[location.pathname] ?? meta['/dashboard']
  const searchResult = useMemo(() => query.trim().toLowerCase().includes('theft') ? 'crime-map' : query.trim().toLowerCase().includes('patrol') ? 'patrol-planning' : '', [query])
  const handleSubmit = (event: React.FormEvent) => { event.preventDefault(); if (searchResult) navigate(`/${searchResult}`); else if (query.trim()) navigate('/ai-assistant') }
  return <header className="sticky top-0 z-20 flex min-h-[64px] items-center justify-between gap-4 border-b border-border bg-ink px-5 lg:px-7"><div className="flex min-w-0 items-center gap-3"><button onClick={onMenu} className="border border-border p-1.5 text-muted hover:text-warm lg:hidden"><Menu size={15} /></button><div className="hidden border-r border-border pr-4 sm:block"><div className="mono text-[9px] font-medium text-warm">PDC / OPS</div><div className="mono mt-0.5 text-[8px] text-muted">SECURE CONSOLE</div></div><div className="min-w-0"><div className="eyebrow truncate">{current.crumb}</div><h1 className="mt-0.5 truncate text-[16px] font-semibold tracking-[-.02em] text-warm">{current.title}</h1></div></div><form onSubmit={handleSubmit} className="hidden min-w-[260px] max-w-[480px] flex-1 md:block"><div className="group flex h-8 items-center gap-2 border border-border bg-panel px-2.5 transition-colors focus-within:border-[#62696d]"><Search size={13} className="text-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Query intelligence, location or incident ID" className="min-w-0 flex-1 bg-transparent text-[10px] text-warm outline-none placeholder:text-muted/70" /><kbd className="mono border border-border px-1 text-[8px] text-muted">/</kbd></div></form><div className="flex items-center gap-3"><div className="hidden items-center gap-2 border-r border-border pr-3 sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#8db69a]" /><span className="mono text-[9px] text-muted">LIVE / 19:42 IST</span></div><Button variant="ghost" size="sm" className="h-7 w-7 p-0"><Bell size={14} /></Button><div className="flex items-center gap-2"><div className="flex h-7 w-7 items-center justify-center border border-[#62696d] bg-panel text-warm"><ShieldCheck size={14} /></div><div className="hidden leading-tight lg:block"><div className="text-[10px] font-medium text-warm">Inspector</div><div className="mono mt-0.5 text-[8px] text-muted">WHITE TOWN PS</div></div></div></div></header>
}
